### ISSUE TITLE
do different plot treatments have different plant communities?

### ISSUE THREAD

**Issue by emchristensen** [emchristensen/PlotSwitch#11]
Need some sort of analysis (pcca?) of whether plants still differ by rodent treatment just before the switch (i.e., could the indirect effect of rodents changing plant community contribute to the reduced ability of dipodomys to re-invade plots)

**Comment by gavinsimpson** [comment]
How many samples per treatment of plant composition data constitute the "just before" period?

**Comment by emchristensen** [comment]
If we use ALL the plots (i.e. not just the 10 plots we're using for the rodent analyses), we have 10 controls, 8 krat exclosures, and 6 total rodent exclosures (per year). The treatment switch was done in 2015, and we have plant data for winter annual plants 2011-2015, and summer annual plants 2014, 2011, 2008 (there were some unfortunate funding gaps). I played around with a pcca with this data in https://github.com/emchristensen/PlotSwitch/blob/master/plant_ordination_analysis.R and my impression is that there's a huge amount of year-to-year variation in these communities, and maybe a small effect from treatment. Not 100% sure if this is the best way to look at this... open to suggestions
